# Training configuration for image segmentation

# Project settings
project: "cgras_segmentation"
name: "train_amag130"
model_path: "/media/java/RRAP03/models/yolov8n-seg.pt"
yaml_path: "/media/java/RRAP03/data/outputs/data_pipleline/amag130_filtered_split_tiled_balanced/cgras_data.yaml"

# Training parameters
classes: [0, 1, 2, 3]  # Coral and Polyp
pretrained: true
epochs: 1000
batch_size: 0.75
workers: 4
save_period: 10
patience: 25
mask_overlap: false
device: 0  # device = [0, 1, 2, 3]

# Augmentation parameters
image_size: 640
scale: 0.2
flipud: 0.5
fliplr: 0.5