# Dataset paths
data_location: '/mnt/hpccs01/home/wardlewo/Data/cgras/Cgras_2023_dataset_labels_updated/20250318_improved_label_dataset_split_subimages/test'
save_dir_for_split: '/mnt/hpccs01/home/wardlewo/Data/Test/Test_split'
final_output_dir: '/mnt/hpccs01/home/wardlewo/Data/Test/Final_output'

# Dataset split ratios
train_ratio: 0.70
test_ratio: 0.15
valid_ratio: 0.15

# Tiling parameters
tile_width: 640
tile_height: 640
truncate_percent: 0.5
tile_overlap: null  # Will be calculated based on tile dimensions and truncate_percent
max_files_per_dir: 16382
workers: null  # Uses CPU count if null

# Balancing parameters
balance_dataset: true
