# CGRAS Data Processing Pipeline Configuration

# Project details
project_name: "amil_test"  # Name of the project
input_path: "data/amil/cvat_outputs/amil_test/cgras_data.yaml"  # Absolute path to the input data from CVAT
output_base_path: "data/amil/segmentation_outputs/amil_test_3"  # Base output directory

# Pipeline steps to run (in order)
pipeline:
  - folder_structure
  - filter
  - split
  - patch
  - balance

# Step-specific configurations
folder_structure:
  enabled: true  # Set to false to skip this step

filter:
  enabled: true
  class_ids: [0, 1]  # Classes to filter
  min_pixel_area: [200, 200] # Different thresholds for different classes
  copy_images: true  # Whether to copy image files or just labels

split:
  enabled: true
  split_field: "tile"  # Field to split by (e.g., tile, week)
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  stratify_by: null  # Field to stratify by (null for no stratification)
  random_seed: 42

patch:
  enabled: true
  tile_width: 640
  tile_height: 640
  truncate_percent: 0.5  # Minimum percentage of object that must be in tile # check whether we still want this
  max_files: 16382  # Maximum files per directory
  min_viable_area: 20.0  # Minimum area for split objects in pixels²
  min_fraction: 0.1  # Minimum fraction of original polygon for split objects

balance:
  enabled: true