# CGRAS Data Processing Pipeline Configuration

# Project details
project_name: "pdae_early10"  # Name of the project
input_path: "data/cgras/cvat_imports/pdae_early_stage"  # Absolute path to the input data from CVAT
output_base_path: "data/cgras/pdae_early10"  # Base output directory

# Pipeline steps to run (in order)
pipeline:
  - folder_structure
  - filter
  - split
  - patch
  - balance

# Step-specific configurations
folder_structure:
  enabled: true  # Set to false to skip this step

filter:
  enabled: true
  class_ids: [0, 1]  # Classes to filter
  min_pixel_area: [200, 200] # Different thresholds for different classes
  copy_images: true  # Whether to copy image files or just labels

split:
  enabled: true
  split_field: "tile"  # Field to split by (e.g., tile, week)
  train_ratio: 0.5
  val_ratio: 0.10
  test_ratio: 0.40
  stratify_by: null  # Field to stratify by (null for no stratification)
  random_seed: 42

patch:
  enabled: true
  tile_width: 640
  tile_height: 640
  truncate_percent: 0.5  # Minimum percentage of object that must be in tile # check whether we still want this
  max_files: 16382  # Maximum files per directory

balance:
  enabled: true